camunda.bpm:
  metrics.enabled: false
  history-level: auto

  database:
    schema-update: drop-create
    type: h2

server:
  port: 8082

eventServiceBaseUrl: http://localhost:8081

eureka:
  client:
    healthcheck:
      enabled: true

endpoints:
  info:
    enabled: true

info:
  app:
    engine: camunda
    version: 7.4
    instance: trivialEngine
