server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    ipAddress: ${DOCKER_IP:127.0.0.1}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ipAddress}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
