eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

endpoints:
  info:
    enabled: true

zuul:
  debug:
    request: true
  routes:
    workloadservice:
      path: /eventservice/**
      serviceId: workloadservice
    simpleprocess:
      path: /simpleprocess/**
      serviceId: simpleprocess
    trivialprocess:
      path: /trivialprocess/**
      serviceId: trivialprocess

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 20000

logging:
  level:
    com:
      netflix: debug
