sudo: false

language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=0.12

install: true

install:
  - nvm install $NODE_VERSION

cache:
  directories:
    - $HOME/.m2

script:
    - nvm use $NODE_VERSION
    - ./mvnw clean install
