version: '2'
services:
  discovery:
    image: camunda-bpm-cloud/camunda-bpm-cloud-discovery-service
    ports:
      - "8761:8761"

  configserver:
    image: camunda-bpm-cloud/camunda-bpm-cloud-config-service
    ports:
      - "8888:8888"

  edgeservice:
    image: camunda-bpm-cloud/camunda-bpm-cloud-edge-service
    ports:
      - "8082:8082"

  workloadservice:
    image: camunda-bpm-cloud/camunda-bpm-cloud-workload-service

  simpleprocess:
    image: camunda-bpm-cloud/camunda-bpm-cloud-example-simple-process

  trivialprocess:
    image: camunda-bpm-cloud/camunda-bpm-cloud-example-trivial-process

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=camunda
      - MYSQL_PASSWORD=camunda
      - CAMUNDA_DATABASES=simpleprocess,trivialprocess
    ports:
      - "3306:3306"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
