server:
  port: 8082

eureka:
  instance:
    hostname: edgeservice
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

endpoints:
  info:
    enabled: true

zuul:
  debug:
    request: true
  routes:
    eventservice:
      path: /eventservice/**
      serviceId: eventService
    simpleprocess:
      path: /simpleEngine/**
      # serviceId: simpleEngine
      url: http://simpleprocess:9998
    trivialprocess:
      path: /trivialEngine/**
      serviceId: trivialEngine

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 20000

logging:
  level:
    com:
      netflix: debug
