server:
  port: 8888

spring:
  profiles:
    active: native
  application:
      name: configServer

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://discovery:8761/eureka/"
