eureka:
  client:
    healthcheck:
      enabled: true

endpoints:
  info:
    enabled: true

camunda.bpm:
  metrics.enabled: false
  history-level: auto
  database:
    schema-update: drop-create
    type: h2
