info:
  app:
    engine: camunda
    version: 7.5
    instance: simpleEngine

eureka:
  instance:
    metadata-map:
      engine: camunda

#server:
#  port: 0

eventServiceBaseUrl: "http://eventservice:8081"
