info:
  app:
    engine: camunda
    version: 7.5
    instance: simpleprocess

eureka:
  instance:
    metadata-map:
      engine: camunda

eventServiceBaseUrl: "http://eventservice:8081"


spring.datasource:
  url: jdbc:mysql://mysql:3306/${spring.application.name}
  username: camunda
  password: camunda
