spring:
  application:
    name: cloudtasklist
server:
  port: 9001

zuul:
  debug:
    request: true
  routes:
    tasklist:
      path: /workload/**
      url: ${workloadqueryservice.url}
      # http://${DOCKER_IP:localhost}:8082/eventservice/
