spring:
  application:
    name: simple-process
  datasource:
    url: jdbc:mysql://${camunda.bpm.cloud.hostname.mysql}:3306/${spring.application.name}?useSSL=false
    username: camunda
    password: camunda
  rabbitmq:
    host: ${camunda.bpm.cloud.hostname.rabbitmq}
    username: pcf
    password: pcf


endpoints:
  info:
    enabled: false

info:
  app:
    engine: camunda
    version: 7.6
    instance: ${spring.application.name}

camunda:
  bpm:
    cloud:
      name: ${spring.application.name}
      amqp:
        prefix: camunda-task
        queue:
          command: ${camunda.bpm.cloud.amqp.prefix}-command
          event: ${camunda.bpm.cloud.amqp.prefix}-event
        exchange:
          command: ${camunda.bpm.cloud.amqp.queue.command}-exchange
          event: ${camunda.bpm.cloud.amqp.queue.event}-exchange
    metrics:
      enabled: false
    history-level: auto
    database:
      schema-update: true
      type: mysql
    id-generator: prefixed
