eureka:
  client:
    healthcheck:
      enabled: true

endpoints:
  info:
    enabled: true

camunda:
  bpm:
    cloud:
      hostname:
        mysql: mysql
        discovery: discovery
        configserver: configserver
        rabbitmq: rabbitmq
      amqp:
        queue: task-event
        exchange: task-event-exchange
