# activate via spring.profiles.activate=camunda when implementing a process engine
info:
  app:
    engine: camunda
    version: 7.5
    instance: ${spring.application.name}

eureka:
  instance:
    metadata-map:
      engine: camunda

spring.datasource:
  url: jdbc:mysql://${camunda.bpm.cloud.hostname.mysql}:3306/${spring.application.name}?useSSL=false
  username: camunda
  password: camunda

camunda.bpm:
  metrics.enabled: false
  history-level: auto
  database:
    schema-update: false
    type: mysql
