spring:
  profiles:
    include: registerwitheureka

zuul:
  debug:
    request: true
  routes:
    workloadservice:
      path: /eventservice/**
      serviceId: workloadqueryservice
    simpleprocess:
      path: /simpleprocess/**
      serviceId: simpleprocess
    trivialprocess:
      path: /trivialprocess/**
      serviceId: trivialprocess

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 20000

logging:
  level:
    com:
      netflix: debug
