spring:
  profiles:
    include: registerwitheureka
  rabbitmq:
      host: ${camunda.bpm.cloud.hostname.rabbitmq}
  datasource:
    url: jdbc:mysql://${camunda.bpm.cloud.hostname.mysql}:3306/eventstore?useSSL=false
    username: camunda
    password: camunda
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

axon:
  amqp:
    exchange: ${camunda.bpm.cloud.amqp.exchange.event}
#  eventhandling:
#    processors:

