spring:
  profiles:
    include: registerwitheureka
  rabbitmq:
      host: ${camunda.bpm.cloud.hostname.rabbitmq}
  datasource:
    url: jdbc:h2:./data/${spring.application.name};AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

axon:
  amqp:
    exchange: ${camunda.bpm.cloud.amqp.exchange.event}

