spring:
  profiles:
    include: registerwitheureka, amqp
  datasource:
    url: jdbc:h2:./data/${spring.application.name};AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

#axon:
#  eventhandling:
#    processors:
#      - "org.camunda.bpm.extension.cloud.workload.query.service.handler"
