server:
  port: 8081

eureka:
  instance:
    hostname: eventservice
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

endpoints:
  info:
    enabled: true
